include:
  - ../greptimedb-common.yml

services:
  init_database:
    image: docker.io/postgres:17
    networks:
      - demo-network
    depends_on:
      greptimedb:
        condition: service_healthy
    volumes:
      - ./init.sql:/init.sql
    entrypoint: sh -c "sleep 10 && psql -h greptimedb -p 4003 -d public -f /init.sql"
    environment:
      PGSSLMODE: disable
    init: yes

  django:
    build: django-app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=*
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://greptimedb:4000/v1/otlp/v1/traces

  client:
    build: todo-client/
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://greptimedb:4000/v1/otlp/v1/traces
      - BASE_URL=http://django:8000
    depends_on:
      - django

  grafana:
    image: docker.io/grafana/grafana:12.3.0
    ports:
      - 3000:3000
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning

networks:
  demo-network:
